// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTDaKLyfxWqvZXqhLSgSS7cJskJurmuyM',
    appId: '1:857388856744:android:5cb917c81a143cc230199d',
    messagingSenderId: '857388856744',
    projectId: 'neapoliscar-991a1',
    databaseURL: 'https://neapoliscar-991a1-default-rtdb.firebaseio.com',
    storageBucket: 'neapoliscar-991a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZhF7VY4UaxMEkX8ueQJ52-NOZDvDuVwc',
    appId: '1:857388856744:ios:bf91fc76f3720bdd30199d',
    messagingSenderId: '857388856744',
    projectId: 'neapoliscar-991a1',
    databaseURL: 'https://neapoliscar-991a1-default-rtdb.firebaseio.com',
    storageBucket: 'neapoliscar-991a1.appspot.com',
    iosBundleId: 'com.example.neapolisAdmin',
  );
}
